apiVersion: v1
kind: Service
metadata:
  name: orders-service
  namespace: orders
  labels:
    app: orders
spec:
  type: ClusterIP
  selector:
    app: orders
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
